// Table de correction phonétique pour TTS (ElevenLabs / AppelResto)
// Généré à partir de la liste des prénoms arabes (prenomeo.com)
// Clé = prénom original (tel qu'en base) | Valeur = orthographe à envoyer au TTS
//
// Les catégories KH, GH et W sont marquées "à tester au cas par cas" dans la
// source : leur `phonetic` est identique à `original` (suffixé de * ou **)
// pour signaler l'incertitude, pas une vraie substitution. PHONETIC_MAP (en
// bas de fichier) retire ce suffixe pour ne jamais envoyer d'astérisque au TTS.

export type PhoneticCorrection = {
  original: string;
  phonetic: string;
  category: string;
};

export const PHONETIC_CORRECTIONS: PhoneticCorrection[] = [
  // --- Digramme AY/EY (lu comme 'è' au lieu de 'ai') — correction fiable ---
  { original: 'Aya', phonetic: 'Aïa', category: 'AY/EY' },
  { original: 'Ayham', phonetic: 'Aiham', category: 'AY/EY' },
  { original: 'Aylan', phonetic: 'Ailan', category: 'AY/EY' },
  { original: 'Ayman', phonetic: 'Aiman', category: 'AY/EY' },
  { original: 'Aymane', phonetic: 'Aimane', category: 'AY/EY' },
  { original: 'Aymen', phonetic: 'Aimen', category: 'AY/EY' },
  { original: 'Ayoub', phonetic: 'Aïoub', category: 'AY/EY' },
  { original: 'Ayyub', phonetic: 'Aïyoub', category: 'AY/EY' },
  { original: 'Baya', phonetic: 'Baïa', category: 'AY/EY' },
  { original: 'Bayan', phonetic: 'Baïane', category: 'AY/EY' },
  { original: 'Bayen', phonetic: 'Baïen', category: 'AY/EY' },
  { original: 'Bayram', phonetic: 'Bairam', category: 'AY/EY' },
  { original: 'Bayrem', phonetic: 'Bairem', category: 'AY/EY' },
  { original: 'Beya', phonetic: 'Béïa', category: 'AY/EY' },
  { original: 'Dayan', phonetic: 'Daïane', category: 'AY/EY' },
  { original: 'Daysam', phonetic: 'Daïssam', category: 'AY/EY' },
  { original: 'Faycal', phonetic: 'Faïçal', category: 'AY/EY' },
  { original: 'Fayrouz', phonetic: 'Faïrouz', category: 'AY/EY' },
  { original: 'Fayza', phonetic: 'Faïza', category: 'AY/EY' },
  { original: 'Hayat', phonetic: 'Haïat', category: 'AY/EY' },
  { original: 'Haydar', phonetic: 'Haïdar', category: 'AY/EY' },
  { original: 'Hayet', phonetic: 'Haïette', category: 'AY/EY' },
  { original: 'Haykal', phonetic: 'Haïkal', category: 'AY/EY' },
  { original: 'Haykel', phonetic: 'Haïkel', category: 'AY/EY' },
  { original: 'Haytham', phonetic: 'Haïtham', category: 'AY/EY' },
  { original: 'Inaya', phonetic: 'Inaïa', category: 'AY/EY' },
  { original: 'Ineya', phonetic: 'Inéïa', category: 'AY/EY' },
  { original: 'Jounayd', phonetic: 'Jounaïd', category: 'AY/EY' },
  { original: 'Junayd', phonetic: 'Junaïd', category: 'AY/EY' },
  { original: 'Kaynan', phonetic: 'Kaïnane', category: 'AY/EY' },
  { original: 'Layal', phonetic: 'Laïal', category: 'AY/EY' },
  { original: 'Layana', phonetic: 'Laïana', category: 'AY/EY' },
  { original: 'Layane', phonetic: 'Laïane', category: 'AY/EY' },
  { original: 'Layla', phonetic: 'Laïla', category: 'AY/EY' },
  { original: 'Layth', phonetic: 'Laïth', category: 'AY/EY' },
  { original: 'Leyla', phonetic: 'Leïla', category: 'AY/EY' },
  { original: 'Louay', phonetic: 'Louaï', category: 'AY/EY' },
  { original: 'Loujayn', phonetic: 'Loujaïne', category: 'AY/EY' },
  { original: 'May', phonetic: 'Maï', category: 'AY/EY' },
  { original: 'Maya', phonetic: 'Maïa', category: 'AY/EY' },
  { original: 'Mayada', phonetic: 'Maïada', category: 'AY/EY' },
  { original: 'Maymana', phonetic: 'Maïmana', category: 'AY/EY' },
  { original: 'Maymouna', phonetic: 'Maïmouna', category: 'AY/EY' },
  { original: 'Maysan', phonetic: 'Maïssane', category: 'AY/EY' },
  { original: 'Maysara', phonetic: 'Maïssara', category: 'AY/EY' },
  { original: 'Mayssa', phonetic: 'Maïssa', category: 'AY/EY' },
  { original: 'Mayssae', phonetic: 'Maïssaé', category: 'AY/EY' },
  { original: 'Nayef', phonetic: 'Naïef', category: 'AY/EY' },
  { original: 'Neyla', phonetic: 'Néïla', category: 'AY/EY' },
  { original: 'Noussayba', phonetic: 'Noussaïba', category: 'AY/EY' },
  { original: 'Oubayd', phonetic: 'Oubaïd', category: 'AY/EY' },
  { original: 'Oubayda', phonetic: 'Oubaïda', category: 'AY/EY' },
  { original: 'Ouday', phonetic: 'Oudaï', category: 'AY/EY' },
  { original: 'Oulaya', phonetic: 'Oulaïa', category: 'AY/EY' },
  { original: 'Oumaya', phonetic: 'Oumaïa', category: 'AY/EY' },
  { original: 'Oumeyma', phonetic: 'Ouméïma', category: 'AY/EY' },
  { original: 'Qusay', phonetic: 'Qussaï', category: 'AY/EY' },
  { original: 'Rayan', phonetic: 'Raïane', category: 'AY/EY' },
  { original: 'Rayane', phonetic: 'Raïane', category: 'AY/EY' },
  { original: 'Rayhan', phonetic: 'Raïhane', category: 'AY/EY' },
  { original: 'Rokhaya', phonetic: 'Rokhaïa', category: 'AY/EY' },
  { original: 'Roukaya', phonetic: 'Roukaïa', category: 'AY/EY' },
  { original: 'Sayed', phonetic: 'Saïed', category: 'AY/EY' },
  { original: 'Sayf', phonetic: 'Saïf', category: 'AY/EY' },
  { original: 'Sayfullah', phonetic: 'Saïfoullah', category: 'AY/EY' },
  { original: 'Seyf', phonetic: 'Seïf', category: 'AY/EY' },
  { original: 'Sokayna', phonetic: 'Sokaïna', category: 'AY/EY' },
  { original: 'Soraya', phonetic: 'Soraïa', category: 'AY/EY' },
  { original: 'Souleyman', phonetic: 'Souleïmane', category: 'AY/EY' },
  { original: 'Souleymane', phonetic: 'Souleïmane', category: 'AY/EY' },
  { original: 'Soumaya', phonetic: 'Soumaïa', category: 'AY/EY' },
  { original: 'Souraya', phonetic: 'Souraïa', category: 'AY/EY' },
  { original: 'Tayeb', phonetic: 'Taïeb', category: 'AY/EY' },
  { original: 'Taysir', phonetic: 'Taïssir', category: 'AY/EY' },
  { original: 'Tayssir', phonetic: 'Taïssir', category: 'AY/EY' },
  { original: 'Thoraya', phonetic: 'Thoraïa', category: 'AY/EY' },
  { original: 'Thouraya', phonetic: 'Thouraïa', category: 'AY/EY' },
  { original: 'Touraya', phonetic: 'Touraïa', category: 'AY/EY' },
  { original: 'Zayan', phonetic: 'Zaïane', category: 'AY/EY' },
  { original: 'Zayane', phonetic: 'Zaïane', category: 'AY/EY' },
  { original: 'Zayd', phonetic: 'Zaïd', category: 'AY/EY' },
  { original: 'Zayn', phonetic: 'Zaïne', category: 'AY/EY' },
  { original: 'Zaynab', phonetic: 'Zaïnab', category: 'AY/EY' },
  { original: 'Zeyd', phonetic: 'Zeïd', category: 'AY/EY' },
  { original: 'Zeyn', phonetic: 'Zeïne', category: 'AY/EY' },
  { original: 'Zeyna', phonetic: 'Zeïna', category: 'AY/EY' },
  { original: 'Zoubayr', phonetic: 'Zoubaïr', category: 'AY/EY' },

  // --- Digramme SH (lu 's-h' séparé) — remplacer par CH, correction fiable ---
  { original: 'Bashir', phonetic: 'Bachir', category: 'SH' },
  { original: 'Hashim', phonetic: 'Hachim', category: 'SH' },
  { original: 'Ishak', phonetic: 'Ishak', category: 'SH' },
  { original: 'Ishaq', phonetic: 'Ishak', category: 'SH' },
  { original: 'Rashad', phonetic: 'Rachad', category: 'SH' },
  { original: 'Rashid', phonetic: 'Rachid', category: 'SH' },
  { original: 'Shada', phonetic: 'Chada', category: 'SH' },
  { original: 'Shadi', phonetic: 'Chadi', category: 'SH' },
  { original: 'Shadia', phonetic: 'Chadia', category: 'SH' },
  { original: 'Shafik', phonetic: 'Chafik', category: 'SH' },
  { original: 'Shahid', phonetic: 'Chahid', category: 'SH' },
  { original: 'Shahida', phonetic: 'Chahida', category: 'SH' },
  { original: 'Shaima', phonetic: 'Chaïma', category: 'SH' },
  { original: 'Shakib', phonetic: 'Chakib', category: 'SH' },
  { original: 'Shakir', phonetic: 'Chakir', category: 'SH' },
  { original: 'Shakira', phonetic: 'Chakira', category: 'SH' },
  { original: 'Shams', phonetic: 'Chams', category: 'SH' },
  { original: 'Shamseddine', phonetic: 'Chamseddine', category: 'SH' },
  { original: 'Sharif', phonetic: 'Charif', category: 'SH' },
  { original: 'Sharifa', phonetic: 'Charifa', category: 'SH' },
  { original: 'Sheherazade', phonetic: 'Chéhérazade', category: 'SH' },
  { original: 'Sheikh', phonetic: 'Cheïkh', category: 'SH' },
  { original: 'Sheima', phonetic: 'Cheïma', category: 'SH' },
  { original: 'Shems', phonetic: 'Chems', category: 'SH' },
  { original: 'Shems-Eddine', phonetic: 'Chems Eddine', category: 'SH' },
  { original: 'Shemsa', phonetic: 'Chemsa', category: 'SH' },
  { original: 'Shemseddine', phonetic: 'Chemseddine', category: 'SH' },
  { original: 'Sherazade', phonetic: 'Chérazade', category: 'SH' },
  { original: 'Sherine', phonetic: 'Chérine', category: 'SH' },
  { original: 'Shihab', phonetic: 'Chihab', category: 'SH' },
  { original: 'Shima', phonetic: 'Chima', category: 'SH' },
  { original: 'Shirine', phonetic: 'Chirine', category: 'SH' },

  // --- Digramme TH (lu à l'anglaise) — remplacer par T simple, correction fiable ---
  { original: 'Bouthaina', phonetic: 'Boutaïna', category: 'TH' },
  { original: 'Fathallah', phonetic: 'Fatallah', category: 'TH' },
  { original: 'Fathi', phonetic: 'Fati', category: 'TH' },
  { original: 'Fathia', phonetic: 'Fatia', category: 'TH' },
  { original: 'Fethi', phonetic: 'Feti', category: 'TH' },
  { original: 'Fethia', phonetic: 'Fetia', category: 'TH' },
  { original: 'Ghaith', phonetic: 'Ghaïth', category: 'TH' },
  { original: 'Harith', phonetic: 'Harit', category: 'TH' },
  { original: 'Haytham', phonetic: 'Haïtam', category: 'TH' },
  { original: 'Kalthoum', phonetic: 'Kaltoum', category: 'TH' },
  { original: 'Kaouthar', phonetic: 'Kaoutar', category: 'TH' },
  { original: 'Kaouther', phonetic: 'Kaouter', category: 'TH' },
  { original: 'Laith', phonetic: 'Laït', category: 'TH' },
  { original: 'Layth', phonetic: 'Laït', category: 'TH' },
  { original: 'Leith', phonetic: 'Leït', category: 'TH' },
  { original: 'Othman', phonetic: 'Otmane', category: 'TH' },
  { original: 'Othmane', phonetic: 'Otmane', category: 'TH' },
  { original: 'Thoraya', phonetic: 'Toraïa', category: 'TH' },
  { original: 'Thouraya', phonetic: 'Touraïa', category: 'TH' },
  { original: 'Uthman', phonetic: 'Outmane', category: 'TH' },

  // --- Apostrophe — fait trébucher le TTS ---
  { original: "M'hamed", phonetic: 'Mhamed', category: 'APOSTROPHE' },
  { original: "M'hand", phonetic: 'Mhand', category: 'APOSTROPHE' },

  // --- Trait d'union — pause bizarre, remplacer par espace ---
  { original: 'Fatima-Zahra', phonetic: 'Fatima Zahra', category: 'HYPHEN' },
  { original: 'Mohammed-Ali', phonetic: 'Mohammed Ali', category: 'HYPHEN' },
  { original: 'Mohammed-Amine', phonetic: 'Mohammed Amine', category: 'HYPHEN' },

  // --- Son guttural KH — à tester au cas par cas selon le moteur TTS ---
  { original: 'Cheikh', phonetic: 'Cheïkh', category: 'KH' },
  { original: 'Khadidja', phonetic: 'Khadidja*', category: 'KH' },
  { original: 'Khadija', phonetic: 'Khadija*', category: 'KH' },
  { original: 'Khadra', phonetic: 'Khadra*', category: 'KH' },
  { original: 'Khaled', phonetic: 'Khaled*', category: 'KH' },
  { original: 'Khalid', phonetic: 'Khalid*', category: 'KH' },
  { original: 'Khalifa', phonetic: 'Khalifa*', category: 'KH' },
  { original: 'Khalil', phonetic: 'Khalil*', category: 'KH' },
  { original: 'Khalis', phonetic: 'Khalis*', category: 'KH' },
  { original: 'Khaliss', phonetic: 'Khaliss*', category: 'KH' },
  { original: 'Khamis', phonetic: 'Khamis*', category: 'KH' },
  { original: 'Khaoula', phonetic: 'Khaoula*', category: 'KH' },
  { original: 'Khawla', phonetic: 'Khawla*', category: 'KH' },
  { original: 'Kheira', phonetic: 'Kheira*', category: 'KH' },
  { original: 'Kheireddine', phonetic: 'Kheireddine*', category: 'KH' },
  { original: 'Khelifa', phonetic: 'Khelifa*', category: 'KH' },
  { original: 'Khezia', phonetic: 'Khezia*', category: 'KH' },
  { original: 'Khouloud', phonetic: 'Khouloud*', category: 'KH' },
  { original: 'Lakhdar', phonetic: 'Lakhdar*', category: 'KH' },
  { original: 'Makhlouf', phonetic: 'Makhlouf*', category: 'KH' },
  { original: 'Mikhail', phonetic: 'Mikhail*', category: 'KH' },
  { original: 'Mokhtar', phonetic: 'Mokhtar*', category: 'KH' },
  { original: 'Zoulikha', phonetic: 'Zoulikha*', category: 'KH' },

  // --- Son guttural GH — à tester au cas par cas selon le moteur TTS ---
  { original: 'Baghdad', phonetic: 'Baghdad*', category: 'GH' },
  { original: 'Baligh', phonetic: 'Baligh*', category: 'GH' },
  { original: 'Ghada', phonetic: 'Ghada*', category: 'GH' },
  { original: 'Ghali', phonetic: 'Ghali*', category: 'GH' },
  { original: 'Ghalia', phonetic: 'Ghalia*', category: 'GH' },
  { original: 'Ghanem', phonetic: 'Ghanem*', category: 'GH' },
  { original: 'Ghani', phonetic: 'Ghani*', category: 'GH' },
  { original: 'Ghania', phonetic: 'Ghania*', category: 'GH' },
  { original: 'Ghassan', phonetic: 'Ghassan*', category: 'GH' },
  { original: 'Ghazal', phonetic: 'Ghazal*', category: 'GH' },
  { original: 'Ghazi', phonetic: 'Ghazi*', category: 'GH' },
  { original: 'Ghita', phonetic: 'Ghita*', category: 'GH' },
  { original: 'Ghizlaine', phonetic: 'Ghizlaine*', category: 'GH' },
  { original: 'Ghofran', phonetic: 'Ghofrane*', category: 'GH' },
  { original: 'Ghofrane', phonetic: 'Ghofrane*', category: 'GH' },
  { original: 'Raghad', phonetic: 'Raghad*', category: 'GH' },

  // --- W parfois lu comme V — risque faible, à tester ---
  { original: 'Wadi', phonetic: 'Wadi**', category: 'W' },
  { original: 'Wadia', phonetic: 'Wadia**', category: 'W' },
  { original: 'Wael', phonetic: 'Wael**', category: 'W' },
  { original: 'Wafa', phonetic: 'Wafa**', category: 'W' },
  { original: 'Wafi', phonetic: 'Wafi**', category: 'W' },
  { original: 'Wafik', phonetic: 'Wafik**', category: 'W' },
  { original: 'Wahab', phonetic: 'Wahab**', category: 'W' },
  { original: 'Wahbi', phonetic: 'Wahbi**', category: 'W' },
  { original: 'Wahib', phonetic: 'Wahib**', category: 'W' },
  { original: 'Wahiba', phonetic: 'Wahiba**', category: 'W' },
  { original: 'Wahid', phonetic: 'Wahid**', category: 'W' },
  { original: 'Wahida', phonetic: 'Wahida**', category: 'W' },
  { original: 'Wajdi', phonetic: 'Wajdi**', category: 'W' },
  { original: 'Wajih', phonetic: 'Wajih**', category: 'W' },
  { original: 'Wakil', phonetic: 'Wakil**', category: 'W' },
  { original: 'Wala', phonetic: 'Wala**', category: 'W' },
  { original: 'Walaa', phonetic: 'Walaa**', category: 'W' },
  { original: 'Walid', phonetic: 'Walid**', category: 'W' },
  { original: 'Walida', phonetic: 'Walida**', category: 'W' },
  { original: 'Warda', phonetic: 'Warda**', category: 'W' },
  { original: 'Wassil', phonetic: 'Wassil**', category: 'W' },
  { original: 'Wassila', phonetic: 'Wassila**', category: 'W' },
  { original: 'Wassim', phonetic: 'Wassim**', category: 'W' },
  { original: 'Wassima', phonetic: 'Wassima**', category: 'W' },
  { original: 'Waïl', phonetic: 'Waïl**', category: 'W' },
  { original: 'Wiam', phonetic: 'Wiam**', category: 'W' },
  { original: 'Widad', phonetic: 'Widad**', category: 'W' },
  { original: 'Wided', phonetic: 'Wided**', category: 'W' },
  { original: 'Wiem', phonetic: 'Wiem**', category: 'W' },
  { original: 'Wijdane', phonetic: 'Wijdane**', category: 'W' },
  { original: 'Wissal', phonetic: 'Wissal**', category: 'W' },
  { original: 'Wissale', phonetic: 'Wissale**', category: 'W' },
  { original: 'Wissam', phonetic: 'Wissam**', category: 'W' },
  { original: 'Wissem', phonetic: 'Wissem**', category: 'W' },
];

// Map rapide pour lookup O(1), utilisée pour le texte envoyé au TTS.
// Les suffixes * / ** des catégories "à tester" (KH, GH, W) sont retirés
// ici : ce ne sont que des marqueurs documentaires dans PHONETIC_CORRECTIONS,
// jamais du texte à prononcer.
export const PHONETIC_MAP: Record<string, string> = Object.fromEntries(
  PHONETIC_CORRECTIONS.map((c) => [c.original.toLowerCase(), c.phonetic.replace(/\*+$/, '')])
);
